### ISSUE TITLE
[Suggestion] Use Yarn workspaces

### ISSUE THREAD

**Issue by Maykin-99** [doZennn/steam-rom-manager#251]
Before I start working on the CLI (#58), I'd like to transform this project into [Yarn workspaces](https://yarnpkg.com/features/workspaces).

This would let us cleanly separate code, dependencies and scripts of the GUI and CLI. Shared code would come in one or more separate workspaces.

The suggested file structure would be like this:

```
steam-rom-manager
├── apps
│   ├── cli
│   │   └── package.json
│   └── gui (angular stuff)
│       └── package.json
├── packages
│   ├── (shared-code-1) (e.g. setting management)
│   │   └── package.json
│   └── (shared-code-n) (e.g. image providers)
│       └── package.json
├── package.json
└── yarn.lock
```

As a first step I'd just put most things in `apps/gui` to keep it simple and then bit by bit as the work on the CLI begins and progresses move shared code to `packages/...`.

You might ask: Why not use [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces)? Answer: Never used it and imho npm in general feels more often broken than not.

Feedback is appreciated.

**Comment by cbartondock** [comment]
This is an interesting idea, however I was thinking it might be easier (and easier to maintain in the future) to just build a CLI using yargs that uses message passing to call functions from the GUI. That way we don't have to have two versions of everything we want the CLI to be able to do, although the cost is no doubt the time it takes to run things since it has to spin up the whole electron app.

I checked that this works in practice, just implementing a rudimentary "list all parsers" command along with the default help and version commands in the [yargs-CLI branch](https://github.com/SteamGridDB/steam-rom-manager/tree/yargs-CLI).

**Comment by cbartondock** [comment]
Thinking more about this I'm not sure I'm right. Let me think about it.

**Comment by cbartondock** [comment]
I have decided you're right and to go about it your way. @Maykin-99 if you are interested please join the [SteamGridDB discord](https://discord.gg/kfNqd7rgkt) and dm me over there and I will add you to the SRM developer chat (for discussing PRs etc).

**Comment by cbartondock** [comment]
Ended up taking the yargs-cli approach to implementing a CLI. Not much cause to switch to yarn now.
