### ISSUE TITLE
[Request] Steam Flatpak support

### ISSUE THREAD

**Issue by lhindir** [doZennn/steam-rom-manager#254]
Steam has a Flatpak release that's been getting support from Valve as they work on improving containerization of old games and dependencies. This month, it was first included in Steam's [Linux distribution stats](https://store.steampowered.com/hwsurvey?platform=linux) at over 5% of the Linux market, which will likely increase if Valve continues to invest in it and distributions like Fedora continue to move towards making Flatpak their primary method of installing and sandboxing proprietary user applications.

Tools like [MangoHUD](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud), [Protontricks](https://github.com/flathub/com.github.Matoking.protontricks), and [Proton-GE](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE) already have Flatpaks available for use with the Steam Flatpak, making installation of Steam and these tools a very simple affair on Linux. These examples might be useful to reference if you're interested in making a Flatpak for Steam ROM Manager.

It would be great to see a Flatpak build for Steam ROM Manager in the future. Thanks for your work on this tool!

**Comment by fenglengshun** [comment]
Something that needs to be accounted for is parsing between Flatpak Steam with either Flatpak emulators and/or AppImage emulators.

I actually tried to get [Lutris working with Flatpak emulators](https://github.com/flathub/net.lutris.Lutris/issues/198#issuecomment-989689583) and it was a headache that I couldn't manage to do without potentially taking down most of the sandbox features, as it wasn't build to work with Flatpak emulators.

If there is a Flatpak Steam ROM Manager that can work with parsing between Flatpak and normal Steam, with Flatpak and AppImage emulators, then I think it would be amazing for Steam Deck users and any immutable OS distro like Fedora Silverblue/Kinoite and Endless OS.

**Comment by lhindir** [comment]
Here's [an example](https://www.reddit.com/t8cl1g) of the current difficulties with configuring Steam ROM Manager and Flatpak emulators on SteamOS 3.0. I'm guessing people will run into confusion with the RetroArch Steam release as well. It would probably be good to document these workarounds in lieu of a Flatpak release.

**Comment by cbartondock** [comment]
Am I correct in believing this has been resolved since Flathub accepted SRM?

**Comment by doZennn** [comment]
Yep

**Comment by doZennn** [comment]
Actually nope, lol

**Comment by superjamie** [comment]
This works fine, you just need to grant additional permissions and change the parser.

I only use a Flatpak user install, so all my Flatpak commands are `flatpak --user`. If you have a Flatpak system install, you might need to use `sudo flatpak` instead.

Grant access for Steam ROM Manager to manage the Steam Flatpak folder:

    flatpak --user override --filesystem="~/.var/app/com.valvesoftware.Steam" com.steamgriddb.steam-rom-manager

Grant access for Steam to break out of its Flatpak and run commands on the host OS:  
**Note: Some consider this dangerous as it defeats the purpose of running Steam in a confined Flatpak!**

    flatpak --user override --talk-name=org.freedesktop.Flatpak com.valvesoftware.Steam

In Steam ROM Manager **Settings,** set your **Steam Directory** to the Flatpak's directory:  
(replace `USERNAME` with your actual username)

    /home/USERNAME/.var/app/com.valvesoftware.Steam/.local/share/Steam

In the Steam ROM Manager **Parser**, set the **Executable** to:

    /usr/bin/flatpak-spawn

In the Steam ROM Manager **Parser**, add to the front of **Arguments**:

    --host /usr/bin/flatpak

For example, my full PPSSPP **Parser Arguments** is:

    --host /usr/bin/flatpak run org.ppsspp.PPSSPP "${filePath}"

If you run a native emulator installed on the host, then set that as the Argument instead, eg:

    --host /path/to/emulator --options-for-your-emulator "${filePath}"

Then use SRM as usual. Set your ROM directory, Glob, Controller config, Preview, Parse, and Save To Steam.

Automating this for SRM users is not fully possible.

SRM could add the permissions to its own Flatpak to always manage the Steam directory in `~/.var/app/com.valvesoftware.Steam` because SRM owns the permissions of its own Flatpak. (I am not sure if Flathub will allow one Flatpak to ship with permission to manage another Flatpak, that doesn't seem like good security practice)

However, SRM can't change Steam's talk permissions because Valve own the permissions of the Steam Flatpak. That step would need to be documented within SRM, or maybe SRM could add a GUI option to apply it, keeping in mind that some Steam Flatpak will be user installs and some will be system installs which need root permissions.

References:

* [Steam Community Guide - Using Steam in a Flatpak](https://steamcommunity.com/sharedfiles/filedetails/?id=2615011323)
* https://github.com/flathub/com.valvesoftware.Steam/issues/935

**Comment by Grizzlord** [comment]
> This works fine, you just need to grant additional permissions and change the parser.
> 
> I only use a Flatpak user install, so all my Flatpak commands are `flatpak --user`. If you have a Flatpak system install, you might need to use `sudo flatpak` instead.
> 
> Grant access for Steam ROM Manager to manage the Steam Flatpak folder:
> 
> ```
> flatpak --user override --filesystem="~/.var/app/com.valvesoftware.Steam" com.steamgriddb.steam-rom-manager
> ```
> 
> Grant access for Steam to break out of its Flatpak and run commands on the host OS: **Note: Some consider this dangerous as it defeats the purpose of running Steam in a confined Flatpak!**
> 
> ```
> flatpak --user override --talk-name=org.freedesktop.Flatpak com.valvesoftware.Steam
> ```
> 
> In Steam ROM Manager **Settings,** set your **Steam Directory** to the Flatpak's directory: (replace `USERNAME` with your actual username)
> 
> ```
> /home/USERNAME/.var/app/com.valvesoftware.Steam/.local/share/Steam
> ```
> 
> In the Steam ROM Manager **Parser**, set the **Executable** to:
> 
> ```
> /usr/bin/flatpak-spawn
> ```
> 
> In the Steam ROM Manager **Parser**, add to the front of **Arguments**:
> 
> ```
> --host /usr/bin/flatpak
> ```
> 
> For example, my full PPSSPP **Parser Arguments** is:
> 
> ```
> --host /usr/bin/flatpak run org.ppsspp.PPSSPP "${filePath}"
> ```
> 
> If you run a native emulator installed on the host, then set that as the Argument instead, eg:
> 
> ```
> --host /path/to/emulator --options-for-your-emulator "${filePath}"
> ```
> 
> Then use SRM as usual. Set your ROM directory, Glob, Controller config, Preview, Parse, and Save To Steam.
> 
> Automating this for SRM users is not fully possible.
> 
> SRM could add the permissions to its own Flatpak to always manage the Steam directory in `~/.var/app/com.valvesoftware.Steam` because SRM owns the permissions of its own Flatpak. (I am not sure if Flathub will allow one Flatpak to ship with permission to manage another Flatpak, that doesn't seem like good security practice)
> 
> However, SRM can't change Steam's talk permissions because Valve own the permissions of the Steam Flatpak. That step would need to be documented within SRM, or maybe SRM could add a GUI option to apply it, keeping in mind that some Steam Flatpak will be user installs and some will be system installs which need root permissions.
> 
> References:
> 
> * [Steam Community Guide - Using Steam in a Flatpak](https://steamcommunity.com/sharedfiles/filedetails/?id=2615011323)
> * [Can't run emulators installed through Flatpak as well flathub/com.valvesoftware.Steam#935](https://github.com/flathub/com.valvesoftware.Steam/issues/935)

Maybe im missing something here but it wont allow for /usr/bin/flatpak-spawn as an executable.

**Comment by cbartondock** [comment]
I'm going to close this issue in light of @superjamie's excellent guide. Regarding your issue @Grizzlord I suspect that in your case `/usr/bin/flatpak-spawn` does not exist, that's the only reason SRM would disallow it as an executable.

**Comment by fenglengshun** [comment]
I just saw that there's a guide now - that's great! @cbartondock can you add the guide to the github wiki, and link it to the readme page? Or maybe @superjamie can submit a PR for it, if they want to. Still, very nice regardless!
