### ISSUE TITLE
Add Origin Games and EA Desktop app games

### ISSUE THREAD

**Issue by Dr4goonD3mon** [doZennn/steam-rom-manager#266]
Hi, I've been using this software for a while and i found that it will be very helpfull to add to the parsers the EA origin games, It will be very helpfull, thanks!

**Comment by cbartondock** [comment]
Origin is up next, I will probably get around to EA eventually.

**Comment by centrivical2** [comment]
Those of us that enjoy the Battlefield series whether its multiplayer or solo campaigns, but dislike the EA app & Origin launchers makes me question is there a way to bypass it?

My cousin gave me Battlefield Hardline over the Thanksgiving holiday and after installing it I was unable to play because he just gave me the disc, he didn't hold on to the case meaning there's no registration key number.

**Comment by cbartondock** [comment]
Origin is dead so I won't be adding Origin. EA Desktop is added as of 2.3.48!
