### ISSUE TITLE
Doesn't work on Ubuntu 18.04 becouse of better-sqlite3

### ISSUE THREAD

**Issue by icetbr** [doZennn/steam-rom-manager#283]
Hi there, just wanted to leave this as a tip. The sqlite3 lib used has a dependency on GLIB-2.9, which is unavailable to some older distros.

I changed to the "official" one, and it worked.

from
`"better-sqlite3": "https://github.com/cbartondock/better-sqlite3",`

to
`"better-sqlite3": "^7.5.1",`

**Comment by cbartondock** [comment]
Unfortunately I had to make my own fork of better-sqlite3 in order to have all of the correct prebuilds available for linux and windows (see https://github.com/JoshuaWise/better-sqlite3/issues/601). The prebuilds are necessary because building sqlite3 on the fly fails in github's build environment (I was never able to ascertain why).

That said I will work on bringing my fork up to date and ditching GLIB-2.9

**Comment by cbartondock** [comment]
Fixed in 2.4.0 (upgraded to latest better-sqlite3).
