### ISSUE TITLE
[Feature Request] Environmental Variables

### ISSUE THREAD

**Issue by miketweaver** [doZennn/steam-rom-manager#292]
Allow environmental variables in `ROMs Directory`

I have some apps, that by default, install to the same default location. It would be nice to allow my to create a config that selects that.
```
${os:win|%AppData%\PolyMC\instances|${os:linux|~/.local/share/PolyMC/instances}}
```

And anyone who deviates from that can set it manually.

**Comment by cbartondock** [comment]
Yeah, currently it is limited to the "environment variables" that are available to the preparser, for example "${srmdir}". I should probably make the os one of them. 

Obviously roms directory can't have all the same variables available to it as for example "glob" because at that point the rom directory isn't known.

**Comment by cbartondock** [comment]
Added the ability to use function variables in fields that accept environment variables.
