### ISSUE TITLE
[FEATURE] Add Arcade collection

### ISSUE THREAD

**Issue by svera** [doZennn/steam-rom-manager#339]
There are collections created for MAME and FBNeo, but this is inconsistent with how other collections are named, which are based on systems, not on specific emulators. As arcade systems encompasses very different hardware, it would be nice to create an `Arcade` collection with all ROMs supported by MAME, FBNeo and maybe other arcade emulators.

**Comment by cbartondock** [comment]
Hmmm, I'm not sure. It's easy enough to do this yourself if that's what you want, but I don't know enough about the arcade emu world to say whether it would be a good default setting. @kencinder or @klepp0906 what do you think? I know you guys have a lot of arcade.

**Comment by svera** [comment]
@cbartondock a similar approach is also used by RetroPie: https://retropie.org.uk/docs/Arcade. My idea is not actually organise games that way by default, but provide an alternative, more consistent naming that the user can opt-in.

**Comment by klepp0906** [comment]
> Hmmm, I'm not sure. It's easy enough to do this yourself if that's what you want, but I don't know enough about the arcade emu world to say whether it would be a good default setting. @kencinder or @klepp0906 what do you think? I know you guys have a lot of arcade.

unfortunately i'm currently using launchbox added to steam to launch arcade stuff instead of direct shortcuts.   that being said, even when I did use shortcuts directly it was all lumped into a self designated arcade collection not via "type" of arcade game (board/manufacturer like i think he's suggesting)

at current, like you said - the only way to make this happen would be manually via lots of separate parsers.  big task, but not unrealistically big.

**Comment by kencinder** [comment]
I'm not even sure what is being asked here, the current Arcade presets are the way they are *because* they aren't system specific.

**Comment by cbartondock** [comment]
I think they just want the preset categories to be `${MAME}` for example rather than `${MAME - Retroarch}` or `${MAME - Some Other Emu}`. But it's ridiculously easy to do yourself, so I am closing this.
