### ISSUE TITLE
Request: ability to selectively add games from a directory. 

### ISSUE THREAD

**Issue by Onkeyuk** [doZennn/steam-rom-manager#350]
I would like to keep my collections to show up in emulation station but have my favourites to show in steam on my steam deck. 

At the moment I have to take all my collection out of the folder. Then add these with SRM and then move my collection back.

I would like to select the titles I want to add in SRM

**Comment by danShumway** [comment]
I was coming here to file the same issue. I'm primarily using Emulation Station to manage the games that I've dumped, but I would like to be able to have a limited selection of them show up in Steam using Steam Rom Manager to generate that list.

The holy grail for this would be the ability to have the parser filter out specifically the games that I've *favorited* in Emulation Station. However, I'm guessing that information is not exposed in a way that's easily accessible, and I know that Steam Rom Manager is meant to work for more than just Emulation Station, so I get why that's probably not feasible to do.

Another thing that would work would be the ability to delete/select specific titles when I generate the app list. I can already when I generate the app list go into each app and edit its information, name, images, etc... while I'm in Steam Rom Manager. Could there be another option added into that UI to exclude/delete that specific app from the list?

I know there are ways for me to do this manually after the fact (or to use *really* specific parsers), but I'm just trying to find out if there's a workflow I can use to make it all a bit easier to maintain.

**Comment by Renari** [comment]
This is technically already possible, you just would need to make a manual parser and then provide a manifest.json for the entries you want to add.

**Comment by danShumway** [comment]
I assume you're referring to [this](https://github.com/SteamGridDB/steam-rom-manager/blob/1e7322f8ec372ecba6b43c1e373fa8506bb7bd49/src/lang/english/markdown/manual-parser-input.md)? It's not a perfect solution, but yeah, seems like it could work.

From my end, I looked into Emulation Station a bit more, and it is actually possible to tell whether a title has been favorited or not, that information gets stuck into an XML file. I understand that Steam Rom Manager is probably not looking to do something like that, I think that's completely understandable -- but it seems like *I* could set up a separate bash script to parse out the games that are favorited, make a manifest.json out of those titles, and then I'd need to regen the list in Steam Rom Manager.

It wouldn't be automatic (although I guess Emulation Station does have hooks that get run on close, so maybe I could make it a bit easier), but at least SRM would still download all the artwork, and that would allow having custom input layouts for each game again, rather than swapping between layouts in Emulation Station. I may write up a quick Bash or Node script to do that, this doesn't seem like it would be too difficult.

Anything I do build would still require you to manually run the parser, because as far as I can tell SRM doesn't have a headless/cli mode, and it requires Steam to be closed anyway. But I'm assuming that favorites lists aren't going to change *too* often. If I do have some time to build it, and it works, I will post back.

**Comment by Onkeyuk** [comment]
That would be amazing Dan if you have time to have a go. Sounds like a great plan

**Comment by danShumway** [comment]
Okay, I fooled around with this a little bit. It looks fairly promising, getting the list of favorites out of EmulationStation is easy. The downside is that for a custom manifest in SRM, each game needs to have its launch command set (what emulator/command-line flags to use when launching the ROM).

Since this is conceptually more integrated with EmulationStation, it makes more sense to use EmulationStation's launch options than to use the hard-coded options in SRM. This is especially the case when you realize that EmulationStation allows setting per-ROM custom emulators. So ideally all of that should be preserved.

What would be ideal here is to launch EmulationStation and to pass in a ROM and have EmulationStation then launch that ROM. Unfortunately, there is not a command line option that I can see to launch EmulationStation and pass it in a game.

I'll think a bit. I could manually extract all of the stuff from EmulationStation's config files, but that would both be a ton of work and be very fragile (I'm not really interested in maintaining yet another list of emulator configs, there's already like 2 or 3 of them floating around between EmulationStation/SRM/EmuDeck). Launching from EmulationStation is the better option -- that way EmulationStation scripts will still work, your playcount/etc... will still get updated. So I'll need to think about it a bit.

**Comment by kencinder** [comment]
This isn't the first time something like this has come up, probably won't be the last, but it IS out of scope for SRM...which is a tool to bulk add games to Steam.
Too much work would go into making it into a tool where you pick and choose games to add, as it's been discussed before this is a feature that will not be added. There are already overrides to exclude titles which isn't any different than if an option was added to exclude elsewhere in SRM, it's far easier to sort ones games as needed, say in a subdirectory so they an still be found by any given app.

**Comment by Onkeyuk** [comment]
This is such a shame that this is out of scope and closed. to me it seems a natural feature but there are work arounds. 
I guess I’ll continue to temporarily move all the roms I dont want out of the folder SRM is scanning or spend the time deleting games I don’t want out of steam after it’s scanned. 
thanks for the reply @kencinder anyway and thanks for all the work in this tool

**Comment by kencinder** [comment]
See https://github.com/SteamGridDB/steam-rom-manager/issues/364#issuecomment-1475018979
