### ISSUE TITLE
Bracket removal doesn't work without fuzzy title match

### ISSUE THREAD

**Issue by missionfloyd** [doZennn/steam-rom-manager#377]
As an example, the no-intro name for Wave Race 64 is `Wave Race 64 - Kawasaki Jet Ski (USA)`.

This doesn't match the fuzzy title `Wave Race 64` and as a result, doesn't remove `(USA)` from the end, whereas `Wave Race 64 (USA)` does.

**Comment by kencinder** [comment]
The issue is that the title is only "Wave Race 64" on Steamgriddb, so there isn't a correct fuzzy match found and the final title is used instead, which is the complete filename including brackets. This can be seen in the log.

You can use a title modifier such as `${/(\(.*?\))/|${title}|}` in title modifier to get the original filename as the final title, minus any brackets and parentheses.
Then you can also force an override to the steamgriddb game ID `39034` for `Wave Race 64 - Kawasaki Jet Ski (USA)` to force it to use the artwork.

Better yet, ask for the name on steamgriddb to reflect the actual game title as per no-intro(I agree with this)
