### ISSUE TITLE
Images redownloading every time app list is generated

### ISSUE THREAD

**Issue by jgarvin** [doZennn/steam-rom-manager#387]
AFAICT, all images are redownloading even if already present everytime the app list is generated. I'm inferring this is what is happening because of how slowly the image providers count is decreasing. Would it be difficult to avoid redownloading images that already exist? It's pretty common to have 1 new ROM you want to add and that's it.

**Comment by SamusAranX** [comment]
Just came here to see if someone else had opened an issue about this already because this, along with https://github.com/SteamGridDB/steam-rom-manager/issues/331, (which has not been fixed, despite the issue being closed) is one of the **biggest** pain points that make me actively dread having to use it to update my game collection.

**Comment by cbartondock** [comment]
SRM is a tool for bulk adding games and artwork. use SGDBoop if you want to change single images. 

That said I'll think about adding a parser setting that only fetches artwork for games that don't currently have artwork.

**Comment by cbartondock** [comment]
@SamusAranX next version will have the ability to import/export artwork choices, so if you're truly worried about losing your choices that should help you.

Also the parser setting "prefer current steam images" really should have done the trick if you were actually saving your choices to steam.

**Comment by cbartondock** [comment]
Just looked into this, if you have "prefer current steam images" the images are not downloading from SGDB, except for the new games. So this is already the default behavior.
