### ISSUE TITLE
Allow removing images

### ISSUE THREAD

**Issue by Martmists-GH** [doZennn/steam-rom-manager#398]
In some situations, the parser can mistake one game for another. In these cases, it's better to have no image than a wrong image. Please add a button to remove artwork from being generated for these games.

**Comment by justaguy3939** [comment]
Seconded. I would also like to say right now this can be accomplished by directly deleting the offending artwork from "Steam\userdata\(localid)\config\grid\", unfortunately, next time you run the parser it'll just attempt to assign the same wrong artwork again, and because SRM parses everything at once every time, excluding a specific title will remove it from Steam altogether instead of leaving it alone, so it's not an ideal solution.

**Comment by cbartondock** [comment]
As a temporary workaround You can use the exception manager to exclude the title, or set the "search title" in the exception manager to something that has no images (I usually do a backtick `)

**Comment by cbartondock** [comment]
Added to exception manager in 2.3.47, ability to only grab local artwork.
