### ISSUE TITLE
Local artwork fails to parse path location if there are any `[...]`in dir name

### ISSUE THREAD

**Issue by Marocco2** [doZennn/steam-rom-manager#404]
For some reason it doesn't effect User's glob but I can reproduce this behavior on Local Artwork Configuration

**Comment by cbartondock** [comment]
This is because brackets are special glob characters. E.g. `dir [12]` matches `dir 1` or `dir 2` not `dir [12]`. This will be addressed in 2.4.8 with the ability to comment out characters: `dir \[12\]` will match `dir [12]`. In addition, if you just browse to the directory all special characters will be automatically escaped.
