### ISSUE TITLE
[suggestion] exception list building in the gui

### ISSUE THREAD

**Issue by Phr3d13** [doZennn/steam-rom-manager#411]
Add check boxes and maybe select all/none buttons that will build an exception list before saving the game list.

**Comment by cbartondock** [comment]
SRM is meant to be a bulk adding tool. The exception manager should work fine to remove a few games per parser, and if you're doing more than that you should re-organize your actual game folders.

**Comment by Boltag0n** [comment]
Oh, so this is where you actually address the bulk thing.

Have you considered...not...requiring people to rebuild their entire folder structure, and instead just giving people the kind of normal "add to steam" function that every other app and tool of this type does? 

Chris! The people _**cry out**_ for a simple right-click "add to steam" function in your parse window! They absolutely do not want to have to pore over exception lists (or just hit "reset" on every exception in their library) just because Prof. Chris Dock insisted that "this must be a bulk adding tool".

I doubt anybody has the faintest idea why it ever would be in the first place.
