### ISSUE TITLE
Trying to add lots of games via SRM causes merging to hang

### ISSUE THREAD

**Issue by jasonmbrown** [doZennn/steam-rom-manager#440]
I tried to merge 11000 games using SRM, but after generating app list, it seems to hang forever on Merging regardless of how long its left. Even when I try to generate just one category of 1000+ games, the program seems to hang about 70%-80%.

I am guessing that one or more of the threads is getting stuck in an infinite loop while merging. I haven't taken a look at the code since I haven't used Node.js before. But I plan to take a look at it. Would it be possible to get a more stable method of merging the VDF file?

**Comment by cbartondock** [comment]
To be honest SRM is not meant to handle that volume of games. Even steam can't handle that volume of (non steam) games. Categories break after about 3000 games.

There's definitely no infinite loop happening lol, but potentially some kind of memory crash if you are over taxing your ram.

Anyway, I'm going to close this issue because it's not really an SRM issue. Like I said, steam can't handle that many games.
