### ISSUE TITLE
Excluding ROMs to be added to certain categories/tags?

### ISSUE THREAD

**Issue by DoubleSergio** [doZennn/steam-rom-manager#538]
Hello, in Steam I use a dynamic category for my games that aren't ROMs where it lists all installed games, problem is when adding ROMs via Steam Rom Manager it is not only added to the category I set it to (for example, PS2), but also that dynamic category, so I have to remove them from it every time I add new ROMs.
Is it possible to exclude a category in the config? If not, I think it would be an useful feature, thank you.

**Comment by cbartondock** [comment]
Sorry, but this isn't possible. If you have a dynamic category in Steam that is set to add all apps, that's exactly what it is going to do. SRM can't change that behavior. What I mean is that SRM is not adding the games to that category, steam is noticing that they appear in the library and then adding them for you, because that's essentially what you asked it to do.

If I were you I would just delete that category, an "all games" category is basically just your library. So not super useful.
