### ISSUE TITLE
DNS Resolution Failure

### ISSUE THREAD

**Issue by nukeith42** [doZennn/steam-rom-manager#554]
Due to the recent change in the patch notes "DNS resolution now happens in SRM and uses caching." This seems to break DNS resolution in cases where only specific DNS servers are allowed on the network. ie only Pi-Hole is allowed to more effectively block ads.

SRM does correctly show the images when looking at the preview. However, when running the "save to steam" option the system DNS is ignored, and every query gives errors.
"Error: queryA ECONNREFUSED cdn2.steamgridddb.com"

**Comment by Gwindalmir** [comment]
I get ETIMEOUT, but everything else you said matches.

I have a specific network setup and block all DNS queries that don't go through my ad/malware blocking and parental control DNS on my router.
SRM stopped working for me sometime since I last updated it. Worse yet, all the images I already had set were removed.

The only reason I even updated was because I was waiting for sameboy support. 😢

Why is an application bypassing the system network configuration?

**Comment by AevumDecessus** [comment]
ce0a0cba913054f5c49b3ed8762dc36e46a42859 should resolve this when the next release happens
