### ISSUE TITLE
No user accounts found on Steam clean install

### ISSUE THREAD

**Issue by anaisbetts** [doZennn/steam-rom-manager#579]
Steam seems to have changed something because on clean installs, I can not get Steam ROM Manager to recognize my user:

```
Parser ID: 168935755458019108
 
Following 1 user account(s) were not found (user must to login to Steam at least once):
  [[ my steam name ]]
 
Warning! No user accounts found, it could be due to one of the reasons below:
 - incorrect Steam directory;
 - no user has ever logged in;
 - Steam does not save user credentials ("Show advanced options -> User accounts -> Use account credentials").
If you're seeing this, preview won't be generated for this configuration.
```

My Steam account is logged in, and I am using the standard Steam directory `C:\Program Files (x86)\Steam`

**Comment by Thraxsis** [comment]
Did you find a fix for this, im  currently having this issue.

**Comment by anaisbetts** [comment]
@Thraxsis I did eventually get it to work but I can't remember how it was fixed, sorry :(

**Comment by boredchick130** [comment]
@Thraxsis did you get this resolved I am having the same problem

**Comment by Thraxsis** [comment]
@boredchick130 I did get this fixed, but I believe it was some user error on my part. Everything I have matched up with the default paths like it should.

**Comment by cbartondock** [comment]
People having this issue, try using the actual account ID instead of the steam login name. Steam should save account credentials locally (if you enable `Show advanced options -> User accounts -> Use account credentials`), but perhaps it is not. In that case your account ID is the string of numbers that is the name of your account folder under `C:\Program Files (x86)\Steam\userdata`.

Regardless I don't think this is an issue SRM can solve, either steam is storing your account info locally or it isn't.
