### ISSUE TITLE
Use path to found glob as "Start in" directory

### ISSUE THREAD

**Issue by rybandrei2014** [doZennn/steam-rom-manager#627]
Hi,

I would like to create parser for linux games that are run using Steam Runtime. Here is my configuration:

{
"parserType": "Glob",
"configTitle": "Steam Runtime - SD",
"steamDirectory": "/home/deck/.steam/steam",
"steamCategory": "${Linux}",
"romDirectory": "/run/media/mmcblk0p1/Steam Runtime",
"executableArgs": "./start",
"executableModifier": "\"${exePath}\"",
"startInDirectory": "${filePath}",
"titleModifier": "${fuzzyTitle}",
"imageProviders": [
"SteamGridDB"
],
"onlineImageQueries": "${${fuzzyTitle}}",
"imagePool": "${fuzzyTitle}",
"userAccounts": {
"specifiedAccounts": ""
},
"executable": {
"path": "/home/deck/.steam/bin32/steam-runtime/run.sh",
"shortcutPassthrough": false,
"appendArgsToExecutable": true
},
"parserInputs": {
"glob": "${title}/**/start"
},
"titleFromVariable": {
"limitToGroups": "",
"caseInsensitiveVariables": false,
"skipFileIfVariableWasNotFound": false,
"tryToMatchTitle": false
},
"fuzzyMatch": {
"replaceDiacritics": true,
"removeCharacters": true,
"removeBrackets": true
},
"controllers": {
"ps4": null,
"ps5": null,
"xbox360": null,
"xboxone": null,
"switch_joycon_left": null,
"switch_joycon_right": null,
"switch_pro": null,
"neptune": null
},
"imageProviderAPIs": {
"SteamGridDB": {
"nsfw": true,
"humor": false,
"styles": [],
"stylesHero": [],
"stylesLogo": [],
"stylesIcon": [],
"imageMotionTypes": [
"static"
]
}
},
"defaultImage": {
"tall": "",
"long": "",
"hero": "",
"logo": "",
"icon": ""
},
"localImages": {
"tall": "/run/media/mmcblk0p1/SteamGrid/${fuzzyTitle}/grid-tall.@(png|PNG|jpg|JPG|jpeg|JPEG|webp|WEBP)",
"long": "/run/media/mmcblk0p1/SteamGrid/${fuzzyTitle}/grid.@(png|PNG|jpg|JPG|jpeg|JPEG|webp|WEBP)",
"hero": "/run/media/mmcblk0p1/SteamGrid/${fuzzyTitle}/hero.@(png|PNG|jpg|JPG|jpeg|JPEG|webp|WEBP)",
"logo": "/run/media/mmcblk0p1/SteamGrid/${fuzzyTitle}/logo.@(png|PNG|jpg|JPG|jpeg|JPEG|webp|WEBP)",
"icon": "/run/media/mmcblk0p1/SteamGrid/${fuzzyTitle}/icon.@(png|PNG|jpg|JPG|jpeg|JPEG|webp|WEBP)"
},
"parserId": "16578998189096927",
"version": 15
}

The provided configuration is invalid because I use variable filePath for "Start in" directory option. Is it possible to somehow parameterize "Start in" directory with path of found glob?

**Comment by cbartondock** [comment]
Unfortunately this isn't currently possible, since SRM is checking that the start in directory is a valid directory (after parsing fixed environment variables like steam directory etc) before it parses the files, so it's a catch 22. I'm not sure I'm willing to sacrifice the "valid directory check" for this additional flexibility, it would also be quite a bit of work to re-factor `file-parser.ts` to make it possible. As it is, it's not possible to have different start in directories per shortcut. With the ROM parser.


It *is* possible with the manual parser, so you could give that a try, or if you want you're welcome to submit a PR making it possible to do per-shortcut start-in-directories, ideally without sacrificing the "valid directory" check in the case where an environment variable like `${fileDir}` isn't used
