### ISSUE TITLE
[REQUEST] Support for old GOG galaxy

### ISSUE THREAD

**Issue by MattiasN86** [doZennn/steam-rom-manager#683]
- **Feature information**
Some gog user still uses the old GOG Galaxy launcher (v1.2.67) because it's more stable on some computers and less bloated. Currently i can't make the gog galaxy profile to work with this version on the latest rom manager.

- **Additional context**
Link to forum post about people not liking the new galaxy: https://www.gog.com/forum/general_beta_gog_galaxy_2.0/how_to_keep_galaxy_v12_client_and_avoid_the_forced_v20_beta_update/page1
Link to the 1.2.67 version:
https://content-system.gog.com/open_link/download?path=/open/galaxy/client/setup_galaxy_1.2.67.58.exe

**Comment by cbartondock** [comment]
I'm not likely to implement this myself but if someone else wants to create the parser they are welcome to, I will merge the PR. This also might be solved by [issue 672](https://github.com/SteamGridDB/steam-rom-manager/issues/672) if I get around to implementing that, but I'm not certain since the registry entries for GOG games might also have changed.
